name: Build JAR

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - run: mvn -B -q clean package
      - uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar
